export const AssetKeys = {
  images: {
    player: "player",
    playerAttack: "player-attack",
    kraken: "kraken",
    krakenAttack: "kraken-attack",
    fusionShark: "fusion-shark",
    fusionSharkAttack: "fusion-shark-attack",
    unfathomableJellyfish: "unfathomable-jellyfish",
    unfathomableJellyfishAttack: "unfathomable-jellyfish-attack",
    // 전투 배경은 정적 베이스(1장) + 그 위에 겹치는 애니메이션 fx 오버레이(8프레임)로 2겹 구성이다.
    backgroundBattleStatic: "background-battle-static",
    backgroundBattleFx: "background-battle-fx",
    // 타이틀 배경은 로고가 포함된 정적 베이스(1장) + 그 위에 겹치는 광원/기포 오버레이(각 8프레임) 3겹 구성이다.
    backgroundTitle: "background-title",
    backgroundTitleOverlay1: "background-title-overlay1",
    backgroundTitleOverlay2: "background-title-overlay2",
    // 수심 변화(피해/잠수) 때 캐릭터 발밑에 잠깐 띄우는 물보라 이펙트.
    effectSpray: "effect-spray",
  },
  animations: {
    playerIdle: "player-idle",
    playerAttack: "player-attack",
    fusionSharkIdle: "fusion-shark-idle",
    fusionSharkAttack: "fusion-shark-attack",
    krakenIdle: "kraken-idle",
    krakenAttack: "kraken-attack",
    unfathomableJellyfishIdle: "unfathomable-jellyfish-idle",
    unfathomableJellyfishAttack: "unfathomable-jellyfish-attack",
    backgroundBattleFxAmbient: "background-battle-fx-ambient",
    backgroundTitleOverlay1Ambient: "background-title-overlay1-ambient",
    backgroundTitleOverlay2Ambient: "background-title-overlay2-ambient",
    effectSpray: "effect-spray-ambient",
  },
  audio: {
    bgmBattle: "bgm-battle",
    bgmTitle: "bgm-title",
    bgmFusionSharkBattle: "bgm-fusion-shark-battle",
    bgmJellyfishBattle: "bgm-jellyfish-battle",
    bgmKrakenBattle: "bgm-kraken-battle",
    sfxCardSelect: "sfx-card-select",
    sfxCardPlay: "sfx-card-play",
    sfxAttack: "sfx-attack",
    sfxDive: "sfx-dive",
    sfxDefend: "sfx-defend",
    sfxDepthDown: "sfx-depth-down",
    sfxSurface: "sfx-surface",
    sfxVictory: "sfx-victory",
    sfxDefeat: "sfx-defeat",
    sfxDeath: "sfx-death",
  },
} as const;
